import { Router } from 'express';
import { rateLimit } from 'express-rate-limit';
import * as c from '../controllers/authController.js';
import * as profile from '../controllers/profileController.js';
import { uploadAvatar, validateAvatar } from '../middleware/uploadAvatarMiddleware.js';
import verifyToken from '../middleware/verifyToken.js';
import { validate as v } from '../middleware/validate.js';
import * as s from '../validators/schemas.js';
const router = Router();
const limit = rateLimit({ windowMs: 15 * 60 * 1000, limit: 40, standardHeaders: 'draft-8', legacyHeaders: false, message: { success: false, message: 'Too many login attempts. Try later.' } });
router.post('/register', limit, v(s.register), c.register);
router.post('/login', limit, v(s.login), c.login);
router.use(verifyToken);
router.get('/me', c.me);
router.patch('/me', v(s.profile), profile.updateProfile);
const profileLimit = rateLimit({ windowMs: 15 * 60 * 1000, limit: 30, standardHeaders: 'draft-8', legacyHeaders: false, message: { success: false, message: 'Too many profile changes. Try later.' } });
router.put('/me/avatar', profileLimit, uploadAvatar, validateAvatar, profile.uploadAvatar);
router.delete('/me/avatar', profileLimit, profile.removeAvatar);
router.patch('/change-password', profileLimit, v(s.changePassword), profile.changePassword);
router.post('/logout', c.logout);
export default router;
