import { test } from 'node:test';
import assert from 'node:assert/strict';
import request from 'supertest';
import sharp from 'sharp';
import { io as connect } from 'socket.io-client';
import { once } from 'node:events';
import { createApplication } from '../app.js';
import { memoryStore } from './helpers/memoryStore.js';

test('profile lifecycle: validated image, replacement, rollback, removal, shared avatars, password/session revocation', async () => {
  const deleted = []; let uploads = 0;
  const media = { async upload(buffer) {
    const meta = await sharp(buffer).metadata(); assert.equal(meta.format, 'webp'); assert.equal(meta.width, 512);
    return { url: `https://res.cloudinary.com/test/${++uploads}.webp`, publicId: `asset-${uploads}` };
  }, async destroy(id) { deleted.push(id); } };
  const store = memoryStore();
  const system = createApplication({ store, media, secret: 'profile-test-secret-at-least-32-characters' });
  await new Promise(resolve => system.server.listen(0, '127.0.0.1', resolve));
  const api = request(system.app); let socket, memberSocket;
  try {
    const password = 'OriginalPass123!';
    const owner = (await api.post('/api/auth/register').send({ name: 'Owner', email: 'owner@profile.test', password }).expect(201)).body;
    const member = (await api.post('/api/auth/register').send({ name: 'Member', email: 'member@profile.test', password }).expect(201)).body;
    const auth = `Bearer ${owner.token}`;
    const project = (await api.post('/api/projects').set('Authorization', auth).send({name:'Profile project'}).expect(201)).body.data;
    await api.post(`/api/projects/${project._id}/members`).set('Authorization', auth).send({email: member.user.email}).expect(200);
    socket = connect(`http://127.0.0.1:${system.server.address().port}`, { transports: ['websocket'], auth: { token: owner.token } });
    await once(socket, 'connect');
    memberSocket = connect(`http://127.0.0.1:${system.server.address().port}`, { transports: ['websocket'], auth: { token: member.token } });
    await once(memberSocket, 'connect');
    const memberEvent = once(memberSocket, 'user:updated');
    const event = once(socket, 'user:updated');
    const image = await sharp({create:{width:10,height:10,channels:3,background:'#722F58'}}).png().toBuffer();
    const uploaded = await api.put('/api/auth/me/avatar').set('Authorization', auth).attach('avatar',image,'avatar.png').expect(200);
    assert.equal(uploaded.body.data.avatarUrl, 'https://res.cloudinary.com/test/1.webp');
    assert.equal('avatar' in uploaded.body.data, false);
    assert.equal((await event)[0].user.avatarUrl, uploaded.body.data.avatarUrl);
    assert.equal((await memberEvent)[0].user.avatarUrl, uploaded.body.data.avatarUrl);
    const task = (await api.post(`/api/projects/${project._id}/tasks`).set('Authorization',auth).send({title:'Avatar task',assignee:owner.user._id}).expect(201)).body.data;
    const fetched = (await api.get(`/api/projects/${project._id}/tasks/${task._id}`).set('Authorization',auth).expect(200)).body.data;
    assert.equal(fetched.assigneeUser.avatarUrl, uploaded.body.data.avatarUrl);
    await api.post(`/api/projects/${project._id}/tasks/${task._id}/comments`).set('Authorization',auth).send({body:'Avatar comment'}).expect(201);
    const comments=(await api.get(`/api/projects/${project._id}/tasks/${task._id}/comments`).set('Authorization',auth).expect(200)).body.data;
    assert.equal(comments[0].authorUser.avatarUrl,uploaded.body.data.avatarUrl);
    const details = (await api.get(`/api/projects/${project._id}`).set('Authorization', auth).expect(200)).body.data;
    assert.equal(details.memberUsers.find(u=>u._id===owner.user._id).avatarUrl,uploaded.body.data.avatarUrl);
    await api.put('/api/auth/me/avatar').set('Authorization', auth).attach('avatar',image,'avatar.png').expect(200);
    assert.deepEqual(deleted,['asset-1']);
    await api.put('/api/auth/me/avatar').set('Authorization', auth).attach('avatar',Buffer.from('not an image'),'avatar.png').expect(400);
    await api.put('/api/auth/me/avatar').set('Authorization', auth).attach('avatar',Buffer.from('<svg/>'),'avatar.svg').expect(400);
    await api.put('/api/auth/me/avatar').set('Authorization', auth).attach('avatar',Buffer.alloc(2*1024*1024+1),'avatar.png').expect(413);
    await api.put('/api/auth/me/avatar').set('Authorization', auth).expect(400);
    await api.put('/api/auth/me/avatar').set('Authorization', auth).attach('other',image,'avatar.png').expect(400);
    await api.put('/api/auth/me/avatar').attach('avatar',image,'avatar.png').expect(401);
    assert.equal(uploads,2);
    const patch=store.patch;
    store.patch = async (type,id,fields) => { if(fields.avatar) throw new Error('Simulated database failure'); return patch.call(store,type,id,fields); };
    await api.put('/api/auth/me/avatar').set('Authorization', auth).attach('avatar',image,'avatar.png').expect(500);
    store.patch=patch;
    assert.ok(deleted.includes('asset-3'));
    assert.equal((await api.get('/api/auth/me').set('Authorization',auth)).body.data.avatarUrl,'https://res.cloudinary.com/test/2.webp');
    await api.delete('/api/auth/me/avatar').set('Authorization', auth).expect(200);
    assert.ok(deleted.includes('asset-2'));
    assert.equal((await api.get('/api/auth/me').set('Authorization',auth)).body.data.avatarUrl,null);
    await api.patch('/api/auth/me').set('Authorization',auth).send({name:'Updated owner'}).expect(200);
    await api.patch('/api/auth/me').set('Authorization',auth).send({email:'other@example.com'}).expect(400);
    const newPassword = 'NewPassword123!';
    await api.patch('/api/auth/change-password').set('Authorization',auth).send({currentPassword:'wrong',newPassword,confirmPassword:newPassword}).expect(400);
    await api.patch('/api/auth/change-password').set('Authorization',auth).send({currentPassword:password,newPassword,confirmPassword:'mismatch'}).expect(400);
    await api.patch('/api/auth/change-password').set('Authorization',auth).send({currentPassword:password,newPassword:password,confirmPassword:password}).expect(400);
    const expired=once(socket,'session:expired'); const disconnected=once(socket,'disconnect');
    await api.patch('/api/auth/change-password').set('Authorization',auth).send({currentPassword:password,newPassword,confirmPassword:newPassword}).expect(200);
    await expired; await disconnected;
    await api.get('/api/auth/me').set('Authorization',auth).expect(401);
    await api.post('/api/auth/login').send({email:owner.user.email,password}).expect(401);
    await api.post('/api/auth/login').send({email:owner.user.email,password:newPassword}).expect(200);
  } finally { socket?.disconnect(); memberSocket?.disconnect(); await new Promise(resolve=>system.io.close(resolve)); }
});

test('Cloudinary unavailable leaves existing avatar intact; failed cleanup is explicit', async () => {
  const store=memoryStore(); let failUpload=false;
  const media={async upload(){if(failUpload) {const error=new Error('Upload unavailable'); error.status=502; throw error;} return {url:'https://example.com/a.webp',publicId:'old'};},async destroy(){throw new Error('Provider unavailable');}};
  const system=createApplication({store,media,secret:'another-secret-with-at-least-32-characters'});
  const api=request(system.app);
  const user=(await api.post('/api/auth/register').send({name:'User',email:'cleanup@example.com',password:'password123'})).body;
  const auth=`Bearer ${user.token}`;
  const image=await sharp({create:{width:2,height:2,channels:3,background:'red'}}).png().toBuffer();
  await api.put('/api/auth/me/avatar').set('Authorization',auth).attach('avatar',image,'a.png').expect(200);
  failUpload=true;
  await api.put('/api/auth/me/avatar').set('Authorization',auth).attach('avatar',image,'a.png').expect(502);
  assert.equal((await api.get('/api/auth/me').set('Authorization',auth)).body.data.avatarUrl,'https://example.com/a.webp');
  const removed=(await api.delete('/api/auth/me/avatar').set('Authorization',auth).expect(200)).body;
  assert.equal(removed.cleanupPending,true); assert.equal(removed.data.avatarUrl,null);
  await new Promise(resolve=>system.io.close(resolve));
});
